#!/bin/sh

if [ ! -f "`command -v nvidia-xconfig`" ]; then
    echo "The command is not present. Install the nvidia driver with the version matching your GPU first."
    exit 1
fi

# See <https://askubuntu.com/a/1255010/766334>:
sudo dpkg-reconfigure -phigh xserver-xorg
sudo nvidia-xconfig

echo "- First, reboot to load the new xorg.conf."
echo "- Next, you must manually set the resolution using the NVIDIA X Server Settings GUI (Apply, then Save & choose merge with existing /etc/X11/xorg.conf generated by the previous commands in this script)."

